// Code generated by Codex from gestalt/sdk/go helper code. DO NOT EDIT.
package indexeddb

import (
	"encoding/json"
	"fmt"
	"math"
	"reflect"
	"strings"
	"time"

	gestalt "github.com/valon-technologies/gestalt/sdk/go"
	proto "github.com/valon-technologies/gestalt/sdk/go/gen/v1"
	"google.golang.org/protobuf/types/known/structpb"
	"google.golang.org/protobuf/types/known/timestamppb"
)

type (
	AgentMessage                   = gestalt.AgentMessage
	AgentMessagePart               = gestalt.AgentMessagePart
	AgentMessagePartImageRef       = gestalt.AgentMessagePartImageRef
	AgentMessagePartToolCall       = gestalt.AgentMessagePartToolCall
	AgentMessagePartToolResult     = gestalt.AgentMessagePartToolResult
	AgentMessagePartType           = gestalt.AgentMessagePartType
	AgentToolRef                   = gestalt.AgentToolRef
	BoundWorkflowAgentTarget       = gestalt.BoundWorkflowAgentTarget
	BoundWorkflowEventTrigger      = gestalt.BoundWorkflowEventTrigger
	BoundWorkflowPluginTarget      = gestalt.BoundWorkflowPluginTarget
	BoundWorkflowRun               = gestalt.BoundWorkflowRun
	BoundWorkflowSchedule          = gestalt.BoundWorkflowSchedule
	BoundWorkflowTarget            = gestalt.BoundWorkflowTarget
	ExternalIdentity               = gestalt.ExternalIdentity
	Subject                        = gestalt.Subject
	WorkflowAccessPermission       = gestalt.WorkflowAccessPermission
	WorkflowActor                  = gestalt.WorkflowActor
	WorkflowAgentStep              = gestalt.WorkflowAgentStep
	WorkflowAgentStepWhen          = gestalt.WorkflowAgentStepWhen
	WorkflowEvent                  = gestalt.WorkflowEvent
	WorkflowEventMatch             = gestalt.WorkflowEventMatch
	WorkflowEventTriggerInvocation = gestalt.WorkflowEventTriggerInvocation
	WorkflowExecutionReference     = gestalt.WorkflowExecutionReference
	WorkflowOutputBinding          = gestalt.WorkflowOutputBinding
	WorkflowOutputDelivery         = gestalt.WorkflowOutputDelivery
	WorkflowOutputValueSource      = gestalt.WorkflowOutputValueSource
	WorkflowRunAsSubject           = gestalt.WorkflowRunAsSubject
	WorkflowRunStatus              = gestalt.WorkflowRunStatus
	WorkflowRunTrigger             = gestalt.WorkflowRunTrigger
	WorkflowScheduleTrigger        = gestalt.WorkflowScheduleTrigger
	WorkflowSignal                 = gestalt.WorkflowSignal
)

const (
	AgentMessagePartTypeUnspecified = gestalt.AgentMessagePartTypeUnspecified
	AgentMessagePartTypeText        = gestalt.AgentMessagePartTypeText
	AgentMessagePartTypeJSON        = gestalt.AgentMessagePartTypeJSON
	AgentMessagePartTypeToolCall    = gestalt.AgentMessagePartTypeToolCall
	AgentMessagePartTypeToolResult  = gestalt.AgentMessagePartTypeToolResult
	AgentMessagePartTypeImageRef    = gestalt.AgentMessagePartTypeImageRef
)

var (
	jsonMarshalerType = reflect.TypeOf((*json.Marshaler)(nil)).Elem()
	timeType          = reflect.TypeOf(time.Time{})
)

// structFromMap converts a Go map into a protobuf Struct.
func structFromMap(value map[string]any) (*structpb.Struct, error) {
	if value == nil {
		value = map[string]any{}
	}
	normalized, err := normalizeJSONObject(value, "struct")
	if err != nil {
		return nil, err
	}
	if normalized == nil {
		return nil, nil
	}
	return structpb.NewStruct(normalized)
}

// structFromAny converts a JSON-compatible object into an optional protobuf Struct.
//
// The input may be nil, a string-keyed map, a struct, or a pointer to one of
// those. Struct fields use their exported field names unless a json tag
// supplies a name; json:"-" skips the field and omitempty skips zero values.
// Anonymous embedded fields must have an explicit json tag name; embedded
// fields are not flattened.
func structFromAny(value any) (*structpb.Struct, error) {
	if value == nil {
		return nil, nil
	}
	normalized, err := normalizeJSONObject(value, "struct")
	if err != nil {
		return nil, err
	}
	if normalized == nil {
		return nil, nil
	}
	return structpb.NewStruct(normalized)
}

// mapFromStruct converts a protobuf Struct into its Go map representation.
func mapFromStruct(value *structpb.Struct) map[string]any {
	if value == nil {
		return nil
	}
	return value.AsMap()
}

// valueFromAny converts a Go JSON-compatible value into a protobuf Value.
func valueFromAny(value any) (*structpb.Value, error) {
	normalized, err := normalizeJSONValue(reflect.ValueOf(value), "value", map[uintptr]string{})
	if err != nil {
		return nil, err
	}
	return structpb.NewValue(normalized)
}

// anyFromValue converts a protobuf Value into its Go representation.
func anyFromValue(value *structpb.Value) any {
	if value == nil {
		return nil
	}
	return value.AsInterface()
}

// valuesFromMap converts a JSON-compatible map into protobuf Value entries.
func valuesFromMap(values map[string]any) (map[string]*structpb.Value, error) {
	if len(values) == 0 {
		return nil, nil
	}
	out := make(map[string]*structpb.Value, len(values))
	for key, value := range values {
		pbValue, err := valueFromAny(value)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", key, err)
		}
		out[key] = pbValue
	}
	return out, nil
}

// mapFromValues converts protobuf Value entries into their Go representation.
func mapFromValues(values map[string]*structpb.Value) map[string]any {
	if len(values) == 0 {
		return nil
	}
	out := make(map[string]any, len(values))
	for key, value := range values {
		if value == nil {
			out[key] = nil
			continue
		}
		out[key] = value.AsInterface()
	}
	return out
}

// timeFromTimestamp converts a protobuf Timestamp into a Go time.
func timeFromTimestamp(value *timestamppb.Timestamp) time.Time {
	if value == nil {
		return time.Time{}
	}
	return value.AsTime()
}

// timePtrFromTimestamp converts an optional protobuf Timestamp into an optional time.
func timePtrFromTimestamp(value *timestamppb.Timestamp) (*time.Time, error) {
	if value == nil {
		return nil, nil
	}
	if err := value.CheckValid(); err != nil {
		return nil, err
	}
	out := value.AsTime()
	return &out, nil
}

func normalizeJSONObject(value any, path string) (map[string]any, error) {
	normalized, err := normalizeJSONValue(reflect.ValueOf(value), path, map[uintptr]string{})
	if err != nil {
		return nil, err
	}
	if normalized == nil {
		return nil, nil
	}
	object, ok := normalized.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("%s: expected JSON object, got %T", path, value)
	}
	return object, nil
}

func normalizeJSONValue(value reflect.Value, path string, seen map[uintptr]string) (any, error) {
	if !value.IsValid() {
		return nil, nil
	}
	for value.Kind() == reflect.Interface || value.Kind() == reflect.Pointer {
		if value.IsNil() {
			return nil, nil
		}
		if value.Kind() == reflect.Pointer {
			ptr := value.Pointer()
			if prior, ok := seen[ptr]; ok {
				return nil, fmt.Errorf("%s: contains cycle through %s", path, prior)
			}
			seen[ptr] = path
			defer delete(seen, ptr)
		}
		value = value.Elem()
	}

	if value.Type() == timeType {
		return nil, fmt.Errorf("%s: time.Time is not JSON-compatible; use timestamp helpers", path)
	}
	if implementsJSONMarshaler(value.Type()) {
		return nil, fmt.Errorf("%s: json.Marshaler values are not accepted in protobuf Struct payloads", path)
	}
	if value.Kind() == reflect.Map || value.Kind() == reflect.Slice {
		if value.IsNil() {
			return nil, nil
		}
		ptr := value.Pointer()
		if ptr != 0 {
			if prior, ok := seen[ptr]; ok {
				return nil, fmt.Errorf("%s: contains cycle through %s", path, prior)
			}
			seen[ptr] = path
			defer delete(seen, ptr)
		}
	}

	switch value.Kind() {
	case reflect.Bool:
		return value.Bool(), nil
	case reflect.String:
		return value.String(), nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return value.Int(), nil
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return value.Uint(), nil
	case reflect.Float32, reflect.Float64:
		number := value.Float()
		if math.IsNaN(number) || math.IsInf(number, 0) {
			return nil, fmt.Errorf("%s: expected finite number", path)
		}
		return number, nil
	case reflect.Map:
		return normalizeJSONMap(value, path, seen)
	case reflect.Slice, reflect.Array:
		if value.Kind() == reflect.Slice && value.IsNil() {
			return nil, nil
		}
		if value.Type().Elem().Kind() == reflect.Uint8 {
			return nil, fmt.Errorf("%s: []byte is not JSON-compatible", path)
		}
		out := make([]any, value.Len())
		for index := 0; index < value.Len(); index++ {
			item, err := normalizeJSONValue(value.Index(index), fmt.Sprintf("%s[%d]", path, index), seen)
			if err != nil {
				return nil, err
			}
			out[index] = item
		}
		return out, nil
	case reflect.Struct:
		return normalizeJSONStruct(value, path, seen)
	default:
		return nil, fmt.Errorf("%s: unsupported JSON value %s", path, value.Type())
	}
}

func implementsJSONMarshaler(valueType reflect.Type) bool {
	if valueType.Implements(jsonMarshalerType) {
		return true
	}
	return valueType.Kind() != reflect.Pointer && reflect.PointerTo(valueType).Implements(jsonMarshalerType)
}

func normalizeJSONMap(value reflect.Value, path string, seen map[uintptr]string) (map[string]any, error) {
	if value.IsNil() {
		return map[string]any{}, nil
	}
	if value.Type().Key().Kind() != reflect.String {
		return nil, fmt.Errorf("%s: map keys must be strings", path)
	}
	out := make(map[string]any, value.Len())
	for _, key := range value.MapKeys() {
		keyString := key.String()
		item, err := normalizeJSONValue(value.MapIndex(key), path+"."+keyString, seen)
		if err != nil {
			return nil, err
		}
		out[keyString] = item
	}
	return out, nil
}

func normalizeJSONStruct(value reflect.Value, path string, seen map[uintptr]string) (map[string]any, error) {
	out := map[string]any{}
	valueType := value.Type()
	for index := 0; index < value.NumField(); index++ {
		field := valueType.Field(index)
		if field.PkgPath != "" {
			continue
		}
		name, omitEmpty, skip, explicitName := jsonFieldName(field)
		if skip {
			continue
		}
		if field.Anonymous && !explicitName {
			return nil, fmt.Errorf("%s.%s: anonymous embedded fields are not flattened; add a json tag name", path, field.Name)
		}
		fieldValue := value.Field(index)
		if omitEmpty && isJSONEmptyValue(fieldValue) {
			continue
		}
		item, err := normalizeJSONValue(fieldValue, path+"."+name, seen)
		if err != nil {
			return nil, err
		}
		out[name] = item
	}
	return out, nil
}

func isJSONEmptyValue(value reflect.Value) bool {
	switch value.Kind() {
	case reflect.Array, reflect.Map, reflect.Slice, reflect.String:
		return value.Len() == 0
	case reflect.Bool:
		return !value.Bool()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return value.Int() == 0
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return value.Uint() == 0
	case reflect.Float32, reflect.Float64:
		return value.Float() == 0
	case reflect.Interface, reflect.Pointer:
		return value.IsNil()
	default:
		return false
	}
}

func jsonFieldName(field reflect.StructField) (name string, omitEmpty bool, skip bool, explicitName bool) {
	tag := field.Tag.Get("json")
	if tag == "-" {
		return "", false, true, false
	}
	parts := strings.Split(tag, ",")
	name = strings.TrimSpace(parts[0])
	explicitName = name != ""
	if name == "" {
		name = field.Name
	}
	for _, option := range parts[1:] {
		if option == "omitempty" {
			omitEmpty = true
		}
	}
	return name, omitEmpty, false, explicitName
}

// NewAgentMessage creates an agent message.
func NewAgentMessage(input AgentMessage) (*AgentMessage, error) {
	metadata, err := agentMapFromAny(input.Metadata)
	if err != nil {
		return nil, err
	}
	parts, err := agentMessagePartsFromInputs(input.Parts)
	if err != nil {
		return nil, err
	}
	return &AgentMessage{
		Role:     input.Role,
		Text:     input.Text,
		Parts:    parts,
		Metadata: metadata,
	}, nil
}

// AgentMessageFromMessage converts an existing protocol message into
// builder input.
func AgentMessageFromMessage(value *AgentMessage) (AgentMessage, error) {
	if value == nil {
		return AgentMessage{}, nil
	}
	parts, err := agentMessagePartInputsFromParts(value.Parts)
	if err != nil {
		return AgentMessage{}, err
	}
	return AgentMessage{
		Role:     value.Role,
		Text:     value.Text,
		Parts:    parts,
		Metadata: value.Metadata,
	}, nil
}

// NewAgentMessagePart creates an agent message part.
func NewAgentMessagePart(input AgentMessagePart) (*AgentMessagePart, error) {
	partType := input.Type
	if partType == AgentMessagePartTypeUnspecified {
		partType = inferAgentMessagePartType(input)
	}
	jsonValue, err := agentMapFromAny(input.JSON)
	if err != nil {
		return nil, err
	}
	toolCall, err := newOptionalAgentToolCall(input.ToolCall)
	if err != nil {
		return nil, err
	}
	toolResult, err := newOptionalAgentToolResult(input.ToolResult)
	if err != nil {
		return nil, err
	}
	return &AgentMessagePart{
		Type:       partType,
		Text:       input.Text,
		JSON:       jsonValue,
		ToolCall:   toolCall,
		ToolResult: toolResult,
		ImageRef:   newOptionalAgentImageRef(input.ImageRef),
	}, nil
}

// AgentMessagePartFromPart converts an existing protocol part into builder input.
func AgentMessagePartFromPart(value *AgentMessagePart) (AgentMessagePart, error) {
	if value == nil {
		return AgentMessagePart{}, nil
	}
	return AgentMessagePart{
		Type:       value.Type,
		Text:       value.Text,
		JSON:       value.JSON,
		ToolCall:   agentToolCallInputPtrFromCall(value.ToolCall),
		ToolResult: agentToolResultInputPtrFromResult(value.ToolResult),
		ImageRef:   agentImageRefInputPtrFromRef(value.ImageRef),
	}, nil
}

// NewAgentMessagePartToolCall creates a tool-call payload.
func NewAgentMessagePartToolCall(input AgentMessagePartToolCall) (*AgentMessagePartToolCall, error) {
	arguments, err := agentMapFromAny(input.Arguments)
	if err != nil {
		return nil, err
	}
	return &AgentMessagePartToolCall{
		ID:        input.ID,
		ToolID:    input.ToolID,
		Arguments: arguments,
	}, nil
}

// NewAgentMessagePartToolResult creates a tool-result payload.
func NewAgentMessagePartToolResult(input AgentMessagePartToolResult) (*AgentMessagePartToolResult, error) {
	output, err := agentMapFromAny(input.Output)
	if err != nil {
		return nil, err
	}
	return &AgentMessagePartToolResult{
		ToolCallID: input.ToolCallID,
		Status:     input.Status,
		Content:    input.Content,
		Output:     output,
	}, nil
}

// NewAgentMessagePartImageRef creates an image-reference payload.
func NewAgentMessagePartImageRef(input AgentMessagePartImageRef) *AgentMessagePartImageRef {
	return &AgentMessagePartImageRef{
		URI:      input.URI,
		MimeType: input.MimeType,
	}
}

// NewAgentToolRef creates an agent tool reference.
func NewAgentToolRef(input AgentToolRef) *AgentToolRef {
	var runAs *Subject
	if input.RunAs != nil {
		copied := *input.RunAs
		runAs = &copied
	}
	var runAsExternalIdentity *ExternalIdentity
	if input.RunAsExternalIdentity != nil {
		copied := *input.RunAsExternalIdentity
		runAsExternalIdentity = &copied
	}
	return &AgentToolRef{
		Plugin:                input.Plugin,
		Operation:             input.Operation,
		Connection:            input.Connection,
		Instance:              input.Instance,
		Title:                 input.Title,
		Description:           input.Description,
		System:                input.System,
		RunAs:                 runAs,
		RunAsExternalIdentity: runAsExternalIdentity,
	}
}

// AgentToolRefFromRef converts an existing protocol tool ref into builder input.
func AgentToolRefFromRef(value *AgentToolRef) AgentToolRef {
	if value == nil {
		return AgentToolRef{}
	}
	var runAs *Subject
	if value.RunAs != nil {
		copied := *value.RunAs
		runAs = &copied
	}
	var runAsExternalIdentity *ExternalIdentity
	if value.RunAsExternalIdentity != nil {
		copied := *value.RunAsExternalIdentity
		runAsExternalIdentity = &copied
	}
	return AgentToolRef{
		Plugin:                value.Plugin,
		Operation:             value.Operation,
		Connection:            value.Connection,
		Instance:              value.Instance,
		Title:                 value.Title,
		Description:           value.Description,
		System:                value.System,
		RunAs:                 runAs,
		RunAsExternalIdentity: runAsExternalIdentity,
	}
}

func agentMessageFromProto(value *proto.AgentMessage) AgentMessage {
	if value == nil {
		return AgentMessage{}
	}
	return AgentMessage{
		Role:     value.GetRole(),
		Text:     value.GetText(),
		Parts:    agentMessagePartsFromProto(value.GetParts()),
		Metadata: mapFromStruct(value.GetMetadata()),
	}
}

func agentMessagePtrsFromProto(values []*proto.AgentMessage) []*AgentMessage {
	if len(values) == 0 {
		return nil
	}
	out := make([]*AgentMessage, 0, len(values))
	for _, value := range values {
		native := agentMessageFromProto(value)
		out = append(out, &native)
	}
	return out
}

func agentMessageToProto(value AgentMessage) (*proto.AgentMessage, error) {
	metadata, err := structFromAny(value.Metadata)
	if err != nil {
		return nil, err
	}
	parts, err := agentMessagePartsToProto(value.Parts)
	if err != nil {
		return nil, err
	}
	return &proto.AgentMessage{
		Role:     value.Role,
		Text:     value.Text,
		Parts:    parts,
		Metadata: metadata,
	}, nil
}

func agentMessagesToProto(values []AgentMessage) ([]*proto.AgentMessage, error) {
	if len(values) == 0 {
		return nil, nil
	}
	out := make([]*proto.AgentMessage, 0, len(values))
	for _, value := range values {
		pbValue, err := agentMessageToProto(value)
		if err != nil {
			return nil, err
		}
		out = append(out, pbValue)
	}
	return out, nil
}

func agentMessagePartsFromProto(values []*proto.AgentMessagePart) []AgentMessagePart {
	if len(values) == 0 {
		return nil
	}
	out := make([]AgentMessagePart, 0, len(values))
	for _, value := range values {
		out = append(out, agentMessagePartFromProto(value))
	}
	return out
}

func agentMessagePartFromProto(value *proto.AgentMessagePart) AgentMessagePart {
	if value == nil {
		return AgentMessagePart{}
	}
	return AgentMessagePart{
		Type:       AgentMessagePartType(value.GetType()),
		Text:       value.GetText(),
		JSON:       mapFromStruct(value.GetJson()),
		ToolCall:   agentMessagePartToolCallFromProto(value.GetToolCall()),
		ToolResult: agentMessagePartToolResultFromProto(value.GetToolResult()),
		ImageRef:   agentMessagePartImageRefFromProto(value.GetImageRef()),
	}
}

func agentMessagePartsToProto(values []AgentMessagePart) ([]*proto.AgentMessagePart, error) {
	if len(values) == 0 {
		return nil, nil
	}
	out := make([]*proto.AgentMessagePart, 0, len(values))
	for _, value := range values {
		pbValue, err := agentMessagePartToProto(value)
		if err != nil {
			return nil, err
		}
		out = append(out, pbValue)
	}
	return out, nil
}

func agentMessagePartToProto(value AgentMessagePart) (*proto.AgentMessagePart, error) {
	partType := value.Type
	if partType == AgentMessagePartTypeUnspecified {
		partType = inferAgentMessagePartType(value)
	}
	jsonValue, err := structFromAny(value.JSON)
	if err != nil {
		return nil, err
	}
	toolCall, err := agentMessagePartToolCallToProto(value.ToolCall)
	if err != nil {
		return nil, err
	}
	toolResult, err := agentMessagePartToolResultToProto(value.ToolResult)
	if err != nil {
		return nil, err
	}
	return &proto.AgentMessagePart{
		Type:       proto.AgentMessagePartType(partType),
		Text:       value.Text,
		Json:       jsonValue,
		ToolCall:   toolCall,
		ToolResult: toolResult,
		ImageRef:   agentMessagePartImageRefToProto(value.ImageRef),
	}, nil
}

func agentMessagePartToolCallFromProto(value *proto.AgentMessagePartToolCall) *AgentMessagePartToolCall {
	if value == nil {
		return nil
	}
	return &AgentMessagePartToolCall{
		ID:        value.GetId(),
		ToolID:    value.GetToolId(),
		Arguments: mapFromStruct(value.GetArguments()),
	}
}

func agentMessagePartToolCallToProto(value *AgentMessagePartToolCall) (*proto.AgentMessagePartToolCall, error) {
	if value == nil {
		return nil, nil
	}
	arguments, err := structFromAny(value.Arguments)
	if err != nil {
		return nil, err
	}
	return &proto.AgentMessagePartToolCall{
		Id:        value.ID,
		ToolId:    value.ToolID,
		Arguments: arguments,
	}, nil
}

func agentMessagePartToolResultFromProto(value *proto.AgentMessagePartToolResult) *AgentMessagePartToolResult {
	if value == nil {
		return nil
	}
	return &AgentMessagePartToolResult{
		ToolCallID: value.GetToolCallId(),
		Status:     value.GetStatus(),
		Content:    value.GetContent(),
		Output:     mapFromStruct(value.GetOutput()),
	}
}

func agentMessagePartToolResultToProto(value *AgentMessagePartToolResult) (*proto.AgentMessagePartToolResult, error) {
	if value == nil {
		return nil, nil
	}
	output, err := structFromAny(value.Output)
	if err != nil {
		return nil, err
	}
	return &proto.AgentMessagePartToolResult{
		ToolCallId: value.ToolCallID,
		Status:     value.Status,
		Content:    value.Content,
		Output:     output,
	}, nil
}

func agentMessagePartImageRefFromProto(value *proto.AgentMessagePartImageRef) *AgentMessagePartImageRef {
	if value == nil {
		return nil
	}
	return &AgentMessagePartImageRef{
		URI:      value.GetUri(),
		MimeType: value.GetMimeType(),
	}
}

func agentMessagePartImageRefToProto(value *AgentMessagePartImageRef) *proto.AgentMessagePartImageRef {
	if value == nil {
		return nil
	}
	return &proto.AgentMessagePartImageRef{
		Uri:      value.URI,
		MimeType: value.MimeType,
	}
}

func subjectFromProto(value *proto.SubjectContext) *Subject {
	if value == nil {
		return nil
	}
	return &Subject{
		ID:                  value.GetId(),
		Kind:                value.GetKind(),
		CredentialSubjectID: value.GetCredentialSubjectId(),
		DisplayName:         value.GetDisplayName(),
		AuthSource:          value.GetAuthSource(),
		Email:               value.GetEmail(),
	}
}

func subjectToProto(value *Subject) *proto.SubjectContext {
	if value == nil {
		return nil
	}
	return &proto.SubjectContext{
		Id:                  value.ID,
		Kind:                value.Kind,
		CredentialSubjectId: value.CredentialSubjectID,
		DisplayName:         value.DisplayName,
		AuthSource:          value.AuthSource,
		Email:               value.Email,
	}
}

func externalIdentityFromProto(value *proto.ExternalIdentityContext) *ExternalIdentity {
	if value == nil {
		return nil
	}
	return &ExternalIdentity{
		Type: value.GetType(),
		ID:   value.GetId(),
	}
}

func externalIdentityToProto(value *ExternalIdentity) *proto.ExternalIdentityContext {
	if value == nil {
		return nil
	}
	return &proto.ExternalIdentityContext{
		Type: value.Type,
		Id:   value.ID,
	}
}

func agentToolRefFromProto(value *proto.AgentToolRef) AgentToolRef {
	if value == nil {
		return AgentToolRef{}
	}
	return AgentToolRef{
		Plugin:                value.GetPlugin(),
		Operation:             value.GetOperation(),
		Connection:            value.GetConnection(),
		Instance:              value.GetInstance(),
		Title:                 value.GetTitle(),
		Description:           value.GetDescription(),
		System:                value.GetSystem(),
		RunAs:                 subjectFromProto(value.GetRunAs()),
		RunAsExternalIdentity: externalIdentityFromProto(value.GetRunAsExternalIdentity()),
	}
}

func agentToolRefPtrsFromProto(values []*proto.AgentToolRef) []*AgentToolRef {
	if len(values) == 0 {
		return nil
	}
	out := make([]*AgentToolRef, 0, len(values))
	for _, value := range values {
		native := agentToolRefFromProto(value)
		out = append(out, &native)
	}
	return out
}

func agentToolRefToProto(value AgentToolRef) *proto.AgentToolRef {
	return &proto.AgentToolRef{
		Plugin:                value.Plugin,
		Operation:             value.Operation,
		Connection:            value.Connection,
		Instance:              value.Instance,
		Title:                 value.Title,
		Description:           value.Description,
		System:                value.System,
		RunAs:                 subjectToProto(value.RunAs),
		RunAsExternalIdentity: externalIdentityToProto(value.RunAsExternalIdentity),
	}
}

func agentToolRefPtrsToProto(values []*AgentToolRef) []*proto.AgentToolRef {
	if len(values) == 0 {
		return nil
	}
	out := make([]*proto.AgentToolRef, 0, len(values))
	for _, value := range values {
		if value == nil {
			continue
		}
		out = append(out, agentToolRefToProto(*value))
	}
	return out
}

func agentMessageInputsFromMessages(values []*AgentMessage) ([]AgentMessage, error) {
	if len(values) == 0 {
		return nil, nil
	}
	out := make([]AgentMessage, 0, len(values))
	for index, value := range values {
		input, err := AgentMessageFromMessage(value)
		if err != nil {
			return nil, fmt.Errorf("messages[%d]: %w", index, err)
		}
		out = append(out, input)
	}
	return out, nil
}

func agentMessagesFromPtrs(values []*AgentMessage) []AgentMessage {
	if len(values) == 0 {
		return nil
	}
	out := make([]AgentMessage, 0, len(values))
	for _, value := range values {
		if value != nil {
			out = append(out, *value)
		}
	}
	return out
}

func agentMessagePartsFromInputs(values []AgentMessagePart) ([]AgentMessagePart, error) {
	if len(values) == 0 {
		return nil, nil
	}
	out := make([]AgentMessagePart, 0, len(values))
	for index, value := range values {
		part, err := NewAgentMessagePart(value)
		if err != nil {
			return nil, fmt.Errorf("parts[%d]: %w", index, err)
		}
		out = append(out, *part)
	}
	return out, nil
}

func agentMessagePartInputsFromParts(values []AgentMessagePart) ([]AgentMessagePart, error) {
	if len(values) == 0 {
		return nil, nil
	}
	out := make([]AgentMessagePart, 0, len(values))
	for index, value := range values {
		input, err := AgentMessagePartFromPart(&value)
		if err != nil {
			return nil, fmt.Errorf("parts[%d]: %w", index, err)
		}
		out = append(out, input)
	}
	return out, nil
}

func agentToolRefsFromInputs(values []AgentToolRef) []*AgentToolRef {
	if len(values) == 0 {
		return nil
	}
	out := make([]*AgentToolRef, 0, len(values))
	for _, value := range values {
		out = append(out, NewAgentToolRef(value))
	}
	return out
}

func agentToolRefsFromPtrs(values []*AgentToolRef) []AgentToolRef {
	if len(values) == 0 {
		return nil
	}
	out := make([]AgentToolRef, 0, len(values))
	for _, value := range values {
		if value != nil {
			out = append(out, *value)
		}
	}
	return out
}

func inferAgentMessagePartType(input AgentMessagePart) AgentMessagePartType {
	switch {
	case input.ToolCall != nil:
		return AgentMessagePartTypeToolCall
	case input.ToolResult != nil:
		return AgentMessagePartTypeToolResult
	case input.ImageRef != nil:
		return AgentMessagePartTypeImageRef
	case input.JSON != nil:
		return AgentMessagePartTypeJSON
	case input.Text != "":
		return AgentMessagePartTypeText
	default:
		return AgentMessagePartTypeUnspecified
	}
}

func newOptionalAgentToolCall(input *AgentMessagePartToolCall) (*AgentMessagePartToolCall, error) {
	if input == nil {
		return nil, nil
	}
	return NewAgentMessagePartToolCall(*input)
}

func newOptionalAgentToolResult(input *AgentMessagePartToolResult) (*AgentMessagePartToolResult, error) {
	if input == nil {
		return nil, nil
	}
	return NewAgentMessagePartToolResult(*input)
}

func newOptionalAgentImageRef(input *AgentMessagePartImageRef) *AgentMessagePartImageRef {
	if input == nil {
		return nil
	}
	return NewAgentMessagePartImageRef(*input)
}

func agentToolCallInputPtrFromCall(value *AgentMessagePartToolCall) *AgentMessagePartToolCall {
	if value == nil {
		return nil
	}
	return &AgentMessagePartToolCall{
		ID:        value.ID,
		ToolID:    value.ToolID,
		Arguments: value.Arguments,
	}
}

func agentToolResultInputPtrFromResult(value *AgentMessagePartToolResult) *AgentMessagePartToolResult {
	if value == nil {
		return nil
	}
	return &AgentMessagePartToolResult{
		ToolCallID: value.ToolCallID,
		Status:     value.Status,
		Content:    value.Content,
		Output:     value.Output,
	}
}

func agentImageRefInputPtrFromRef(value *AgentMessagePartImageRef) *AgentMessagePartImageRef {
	if value == nil {
		return nil
	}
	return &AgentMessagePartImageRef{
		URI:      value.URI,
		MimeType: value.MimeType,
	}
}

func agentMapFromAny(value any) (map[string]any, error) {
	structValue, err := structFromAny(value)
	if err != nil {
		return nil, err
	}
	return mapFromStruct(structValue), nil
}

// boundWorkflowPluginTargetToProto creates a plugin workflow target.
func boundWorkflowPluginTargetToProto(input BoundWorkflowPluginTarget) (*proto.BoundWorkflowPluginTarget, error) {
	value, err := structFromAny(input.Input)
	if err != nil {
		return nil, err
	}
	return &proto.BoundWorkflowPluginTarget{
		PluginName:     input.PluginName,
		Operation:      input.Operation,
		Input:          value,
		Connection:     input.Connection,
		Instance:       input.Instance,
		CredentialMode: input.CredentialMode,
	}, nil
}

// boundWorkflowPluginTargetFromProto converts an existing protocol target
// into builder input.
func boundWorkflowPluginTargetFromProto(value *proto.BoundWorkflowPluginTarget) BoundWorkflowPluginTarget {
	if value == nil {
		return BoundWorkflowPluginTarget{}
	}
	return BoundWorkflowPluginTarget{
		PluginName:     value.GetPluginName(),
		Operation:      value.GetOperation(),
		Input:          mapFromStruct(value.GetInput()),
		Connection:     value.GetConnection(),
		Instance:       value.GetInstance(),
		CredentialMode: value.GetCredentialMode(),
	}
}

// workflowOutputDeliveryToProto creates a workflow output delivery.
func workflowOutputDeliveryToProto(input WorkflowOutputDelivery) (*proto.WorkflowOutputDelivery, error) {
	var target *proto.BoundWorkflowPluginTarget
	if input.Target != nil {
		value, err := boundWorkflowPluginTargetToProto(*input.Target)
		if err != nil {
			return nil, err
		}
		target = value
	}
	bindings, err := newWorkflowOutputBindings(input.InputBindings)
	if err != nil {
		return nil, err
	}
	return &proto.WorkflowOutputDelivery{
		Target:         target,
		InputBindings:  bindings,
		CredentialMode: input.CredentialMode,
	}, nil
}

// workflowOutputDeliveryFromProto converts an existing protocol delivery
// into builder input.
func workflowOutputDeliveryFromProto(value *proto.WorkflowOutputDelivery) *WorkflowOutputDelivery {
	if value == nil {
		return nil
	}
	var target *BoundWorkflowPluginTarget
	if value.GetTarget() != nil {
		input := boundWorkflowPluginTargetFromProto(value.GetTarget())
		target = &input
	}
	return &WorkflowOutputDelivery{
		Target:         target,
		InputBindings:  workflowOutputBindingInputsFromBindings(value.GetInputBindings()),
		CredentialMode: value.GetCredentialMode(),
	}
}

// boundWorkflowAgentTargetToProto creates an agent workflow target.
func boundWorkflowAgentTargetToProto(input BoundWorkflowAgentTarget) (*proto.BoundWorkflowAgentTarget, error) {
	responseSchema, err := structFromAny(input.ResponseSchema)
	if err != nil {
		return nil, err
	}
	metadata, err := structFromAny(input.Metadata)
	if err != nil {
		return nil, err
	}
	modelOptions, err := structFromAny(input.ModelOptions)
	if err != nil {
		return nil, err
	}
	outputDelivery, err := newOptionalWorkflowOutputDelivery(input.OutputDelivery)
	if err != nil {
		return nil, err
	}
	sessionReadyDelivery, err := newOptionalWorkflowOutputDelivery(input.SessionReadyDelivery)
	if err != nil {
		return nil, err
	}
	messageProtos, err := agentMessagesToProto(input.Messages)
	if err != nil {
		return nil, err
	}
	steps, err := workflowAgentStepsToProto(input.Steps)
	if err != nil {
		return nil, err
	}
	toolRefs := agentToolRefPtrsToProto(agentToolRefsFromInputs(input.ToolRefs))
	return &proto.BoundWorkflowAgentTarget{
		ProviderName:         input.ProviderName,
		Model:                input.Model,
		Prompt:               input.Prompt,
		Messages:             messageProtos,
		ToolRefs:             toolRefs,
		ResponseSchema:       responseSchema,
		Metadata:             metadata,
		TimeoutSeconds:       input.TimeoutSeconds,
		OutputDelivery:       outputDelivery,
		ModelOptions:         modelOptions,
		SessionReadyDelivery: sessionReadyDelivery,
		Steps:                steps,
	}, nil
}

// boundWorkflowAgentTargetFromProto converts an existing protocol target
// into builder input.
func boundWorkflowAgentTargetFromProto(value *proto.BoundWorkflowAgentTarget) BoundWorkflowAgentTarget {
	if value == nil {
		return BoundWorkflowAgentTarget{}
	}
	return BoundWorkflowAgentTarget{
		ProviderName:         value.GetProviderName(),
		Model:                value.GetModel(),
		Prompt:               value.GetPrompt(),
		Messages:             agentMessagesFromPtrs(agentMessagePtrsFromProto(value.GetMessages())),
		ToolRefs:             agentToolRefsFromPtrs(agentToolRefPtrsFromProto(value.GetToolRefs())),
		ResponseSchema:       mapFromStruct(value.GetResponseSchema()),
		Metadata:             mapFromStruct(value.GetMetadata()),
		TimeoutSeconds:       value.GetTimeoutSeconds(),
		OutputDelivery:       workflowOutputDeliveryFromProto(value.GetOutputDelivery()),
		ModelOptions:         mapFromStruct(value.GetModelOptions()),
		SessionReadyDelivery: workflowOutputDeliveryFromProto(value.GetSessionReadyDelivery()),
		Steps:                workflowAgentStepsFromProto(value.GetSteps()),
	}
}

func workflowAgentStepsToProto(input []WorkflowAgentStep) ([]*proto.WorkflowAgentStep, error) {
	if len(input) == 0 {
		return nil, nil
	}
	out := make([]*proto.WorkflowAgentStep, 0, len(input))
	for i := range input {
		step := input[i]
		messages, err := agentMessagesToProto(step.Messages)
		if err != nil {
			return nil, err
		}
		responseSchema, err := structFromAny(step.ResponseSchema)
		if err != nil {
			return nil, err
		}
		modelOptions, err := structFromAny(step.ModelOptions)
		if err != nil {
			return nil, err
		}
		metadata, err := structFromAny(step.Metadata)
		if err != nil {
			return nil, err
		}
		outputDelivery, err := newOptionalWorkflowOutputDelivery(step.OutputDelivery)
		if err != nil {
			return nil, err
		}
		when, err := workflowAgentStepWhenToProto(step.When)
		if err != nil {
			return nil, err
		}
		out = append(out, &proto.WorkflowAgentStep{
			Id:             step.ID,
			Prompt:         step.Prompt,
			Messages:       messages,
			ToolRefs:       agentToolRefPtrsToProto(agentToolRefsFromInputs(step.ToolRefs)),
			ResponseSchema: responseSchema,
			ModelOptions:   modelOptions,
			TimeoutSeconds: step.TimeoutSeconds,
			OutputDelivery: outputDelivery,
			When:           when,
			Metadata:       metadata,
		})
	}
	return out, nil
}

func workflowAgentStepsFromProto(input []*proto.WorkflowAgentStep) []WorkflowAgentStep {
	if len(input) == 0 {
		return nil
	}
	out := make([]WorkflowAgentStep, 0, len(input))
	for _, step := range input {
		if step == nil {
			continue
		}
		out = append(out, WorkflowAgentStep{
			ID:             step.GetId(),
			Prompt:         step.GetPrompt(),
			Messages:       agentMessagesFromPtrs(agentMessagePtrsFromProto(step.GetMessages())),
			ToolRefs:       agentToolRefsFromPtrs(agentToolRefPtrsFromProto(step.GetToolRefs())),
			ResponseSchema: mapFromStruct(step.GetResponseSchema()),
			ModelOptions:   mapFromStruct(step.GetModelOptions()),
			TimeoutSeconds: step.GetTimeoutSeconds(),
			OutputDelivery: workflowOutputDeliveryFromProto(step.GetOutputDelivery()),
			When:           workflowAgentStepWhenFromProto(step.GetWhen()),
			Metadata:       mapFromStruct(step.GetMetadata()),
		})
	}
	return out
}

func workflowAgentStepWhenToProto(input *WorkflowAgentStepWhen) (*proto.WorkflowAgentStepWhen, error) {
	if input == nil {
		return nil, nil
	}
	equals, err := valueFromAny(input.Equals)
	if err != nil {
		return nil, err
	}
	return &proto.WorkflowAgentStepWhen{
		StepId:     input.StepID,
		OutputPath: input.OutputPath,
		Equals:     equals,
	}, nil
}

func workflowAgentStepWhenFromProto(input *proto.WorkflowAgentStepWhen) *WorkflowAgentStepWhen {
	if input == nil {
		return nil
	}
	return &WorkflowAgentStepWhen{
		StepID:     input.GetStepId(),
		OutputPath: input.GetOutputPath(),
		Equals:     anyFromValue(input.GetEquals()),
	}
}

// workflowActorToProto creates workflow actor metadata.
func workflowActorToProto(input WorkflowActor) *proto.WorkflowActor {
	return &proto.WorkflowActor{
		SubjectId:   input.SubjectID,
		SubjectKind: input.SubjectKind,
		DisplayName: input.DisplayName,
		AuthSource:  input.AuthSource,
	}
}

// workflowActorFromProto converts existing workflow actor metadata into
// builder input.
func workflowActorFromProto(value *proto.WorkflowActor) WorkflowActor {
	if value == nil {
		return WorkflowActor{}
	}
	return WorkflowActor{
		SubjectID:   value.GetSubjectId(),
		SubjectKind: value.GetSubjectKind(),
		DisplayName: value.GetDisplayName(),
		AuthSource:  value.GetAuthSource(),
	}
}

// boundWorkflowTargetToProto creates a workflow target.
func boundWorkflowTargetToProto(input BoundWorkflowTarget) (*proto.BoundWorkflowTarget, error) {
	switch {
	case input.Plugin != nil:
		plugin, err := boundWorkflowPluginTargetToProto(*input.Plugin)
		if err != nil {
			return nil, err
		}
		return &proto.BoundWorkflowTarget{Kind: &proto.BoundWorkflowTarget_Plugin{Plugin: plugin}}, nil
	case input.Agent != nil:
		agent, err := boundWorkflowAgentTargetToProto(*input.Agent)
		if err != nil {
			return nil, err
		}
		return &proto.BoundWorkflowTarget{Kind: &proto.BoundWorkflowTarget_Agent{Agent: agent}}, nil
	default:
		return &proto.BoundWorkflowTarget{}, nil
	}
}

// boundWorkflowTargetFromProto converts an existing protocol target into
// builder input.
func boundWorkflowTargetFromProto(value *proto.BoundWorkflowTarget) BoundWorkflowTarget {
	if value == nil {
		return BoundWorkflowTarget{}
	}
	if plugin := value.GetPlugin(); plugin != nil {
		input := boundWorkflowPluginTargetFromProto(plugin)
		return BoundWorkflowTarget{Plugin: &input}
	}
	if agent := value.GetAgent(); agent != nil {
		input := boundWorkflowAgentTargetFromProto(agent)
		return BoundWorkflowTarget{Agent: &input}
	}
	return BoundWorkflowTarget{}
}

// cloneBoundWorkflowTargetProto creates a copy of an existing workflow target
// through the target input builder.
func cloneBoundWorkflowTargetProto(value *proto.BoundWorkflowTarget) (*proto.BoundWorkflowTarget, error) {
	if value == nil {
		return nil, nil
	}
	return boundWorkflowTargetToProto(boundWorkflowTargetFromProto(value))
}

// workflowEventToProto creates a workflow event.
func workflowEventToProto(input WorkflowEvent) (*proto.WorkflowEvent, error) {
	data, err := structFromAny(input.Data)
	if err != nil {
		return nil, err
	}
	extensions, err := valuesFromMap(input.Extensions)
	if err != nil {
		return nil, err
	}
	return &proto.WorkflowEvent{
		Id:              input.ID,
		Source:          input.Source,
		SpecVersion:     input.SpecVersion,
		Type:            input.Type,
		Subject:         input.Subject,
		Time:            timestampFromNonZeroTime(input.Time),
		Datacontenttype: input.DataContentType,
		Data:            data,
		Extensions:      extensions,
	}, nil
}

// workflowEventFromProto converts an existing protocol event into builder input.
func workflowEventFromProto(value *proto.WorkflowEvent) WorkflowEvent {
	if value == nil {
		return WorkflowEvent{}
	}
	return WorkflowEvent{
		ID:              value.GetId(),
		Source:          value.GetSource(),
		SpecVersion:     value.GetSpecVersion(),
		Type:            value.GetType(),
		Subject:         value.GetSubject(),
		Time:            timeFromTimestamp(value.GetTime()),
		DataContentType: value.GetDatacontenttype(),
		Data:            mapFromStruct(value.GetData()),
		Extensions:      mapFromValues(value.GetExtensions()),
	}
}

// cloneWorkflowEventProto creates a copy of an existing workflow event through
// the event input builder.
func cloneWorkflowEventProto(value *proto.WorkflowEvent) (*proto.WorkflowEvent, error) {
	if value == nil {
		return nil, nil
	}
	return workflowEventToProto(workflowEventFromProto(value))
}

// workflowSignalToProto creates a workflow signal.
func workflowSignalToProto(input WorkflowSignal) (*proto.WorkflowSignal, error) {
	payload, err := structFromAny(input.Payload)
	if err != nil {
		return nil, err
	}
	metadata, err := structFromAny(input.Metadata)
	if err != nil {
		return nil, err
	}
	return &proto.WorkflowSignal{
		Id:             input.ID,
		Name:           input.Name,
		Payload:        payload,
		Metadata:       metadata,
		CreatedBy:      workflowActorFromInput(input.CreatedBy),
		CreatedAt:      timestampFromNonZeroTime(input.CreatedAt),
		IdempotencyKey: input.IdempotencyKey,
		Sequence:       input.Sequence,
	}, nil
}

// workflowSignalFromProto converts an existing protocol signal into builder input.
func workflowSignalFromProto(value *proto.WorkflowSignal) WorkflowSignal {
	if value == nil {
		return WorkflowSignal{}
	}
	return WorkflowSignal{
		ID:             value.GetId(),
		Name:           value.GetName(),
		Payload:        mapFromStruct(value.GetPayload()),
		Metadata:       mapFromStruct(value.GetMetadata()),
		CreatedBy:      workflowActorInputPtrFromActor(value.GetCreatedBy()),
		CreatedAt:      timeFromTimestamp(value.GetCreatedAt()),
		IdempotencyKey: value.GetIdempotencyKey(),
		Sequence:       value.GetSequence(),
	}
}

// cloneWorkflowSignalProto creates a copy of an existing workflow signal
// through the signal input builder.
func cloneWorkflowSignalProto(value *proto.WorkflowSignal) (*proto.WorkflowSignal, error) {
	if value == nil {
		return nil, nil
	}
	return workflowSignalToProto(workflowSignalFromProto(value))
}

// workflowScheduleTriggerToProto creates a schedule-trigger run trigger.
func workflowScheduleTriggerToProto(scheduleID string, scheduledFor time.Time) *proto.WorkflowRunTrigger {
	return &proto.WorkflowRunTrigger{Kind: &proto.WorkflowRunTrigger_Schedule{Schedule: &proto.WorkflowScheduleTrigger{
		ScheduleId:   scheduleID,
		ScheduledFor: timestampFromNonZeroTime(scheduledFor),
	}}}
}

// workflowRunTriggerToProto creates a workflow run trigger.
func workflowRunTriggerToProto(input WorkflowRunTrigger) (*proto.WorkflowRunTrigger, error) {
	selected := 0
	if input.Manual {
		selected++
	}
	if input.Schedule != nil {
		selected++
	}
	if input.Event != nil {
		selected++
	}
	if selected == 0 {
		return &proto.WorkflowRunTrigger{}, nil
	}
	if selected > 1 {
		return nil, fmt.Errorf("workflow run trigger must set exactly one trigger kind")
	}
	if input.Manual {
		return &proto.WorkflowRunTrigger{Kind: &proto.WorkflowRunTrigger_Manual{Manual: &proto.WorkflowManualTrigger{}}}, nil
	}
	if input.Schedule != nil {
		return &proto.WorkflowRunTrigger{Kind: &proto.WorkflowRunTrigger_Schedule{Schedule: &proto.WorkflowScheduleTrigger{
			ScheduleId:   input.Schedule.ScheduleID,
			ScheduledFor: timestampFromOptionalTime(input.Schedule.ScheduledFor),
		}}}, nil
	}

	var event *proto.WorkflowEvent
	if input.Event.Event != nil {
		value, err := workflowEventToProto(*input.Event.Event)
		if err != nil {
			return nil, err
		}
		event = value
	}
	return &proto.WorkflowRunTrigger{Kind: &proto.WorkflowRunTrigger_Event{Event: &proto.WorkflowEventTriggerInvocation{
		TriggerId: input.Event.TriggerID,
		Event:     event,
	}}}, nil
}

// workflowRunTriggerFromProto converts an existing protocol trigger into
// builder input.
func workflowRunTriggerFromProto(value *proto.WorkflowRunTrigger) (WorkflowRunTrigger, error) {
	if value == nil {
		return WorkflowRunTrigger{}, nil
	}
	switch kind := value.GetKind().(type) {
	case *proto.WorkflowRunTrigger_Manual:
		return WorkflowRunTrigger{Manual: true}, nil
	case *proto.WorkflowRunTrigger_Schedule:
		if kind.Schedule == nil {
			return WorkflowRunTrigger{}, nil
		}
		scheduledFor, err := timePtrFromTimestamp(kind.Schedule.GetScheduledFor())
		if err != nil {
			return WorkflowRunTrigger{}, err
		}
		return WorkflowRunTrigger{Schedule: &WorkflowScheduleTrigger{
			ScheduleID:   kind.Schedule.GetScheduleId(),
			ScheduledFor: scheduledFor,
		}}, nil
	case *proto.WorkflowRunTrigger_Event:
		if kind.Event == nil {
			return WorkflowRunTrigger{}, nil
		}
		var event *WorkflowEvent
		if kind.Event.GetEvent() != nil {
			input := workflowEventFromProto(kind.Event.GetEvent())
			event = &input
		}
		return WorkflowRunTrigger{Event: &WorkflowEventTriggerInvocation{
			TriggerID: kind.Event.GetTriggerId(),
			Event:     event,
		}}, nil
	default:
		return WorkflowRunTrigger{}, nil
	}
}

// cloneWorkflowRunTriggerProto creates a copy of an existing workflow run
// trigger.
func cloneWorkflowRunTriggerProto(value *proto.WorkflowRunTrigger) (*proto.WorkflowRunTrigger, error) {
	input, err := workflowRunTriggerFromProto(value)
	if err != nil || value == nil {
		return nil, err
	}
	return workflowRunTriggerToProto(input)
}

// boundWorkflowRunToProto creates a bound workflow run.
func boundWorkflowRunToProto(input BoundWorkflowRun) (*proto.BoundWorkflowRun, error) {
	target, err := newOptionalBoundWorkflowTarget(input.Target)
	if err != nil {
		return nil, err
	}
	trigger, err := newOptionalWorkflowRunTrigger(input.Trigger)
	if err != nil {
		return nil, err
	}
	return &proto.BoundWorkflowRun{
		Id:            input.ID,
		Status:        proto.WorkflowRunStatus(input.Status),
		Target:        target,
		Trigger:       trigger,
		CreatedAt:     timestampFromNonZeroTime(input.CreatedAt),
		StartedAt:     timestampFromOptionalTime(input.StartedAt),
		CompletedAt:   timestampFromOptionalTime(input.CompletedAt),
		StatusMessage: input.StatusMessage,
		ResultBody:    input.ResultBody,
		CreatedBy:     workflowActorFromInput(input.CreatedBy),
		ExecutionRef:  input.ExecutionRef,
		WorkflowKey:   input.WorkflowKey,
	}, nil
}

// boundWorkflowRunFromProto converts an existing protocol run into builder input.
func boundWorkflowRunFromProto(value *proto.BoundWorkflowRun) (BoundWorkflowRun, error) {
	if value == nil {
		return BoundWorkflowRun{}, nil
	}
	startedAt, err := timePtrFromTimestamp(value.GetStartedAt())
	if err != nil {
		return BoundWorkflowRun{}, err
	}
	completedAt, err := timePtrFromTimestamp(value.GetCompletedAt())
	if err != nil {
		return BoundWorkflowRun{}, err
	}
	trigger, err := workflowRunTriggerFromProto(value.GetTrigger())
	if err != nil {
		return BoundWorkflowRun{}, err
	}
	return BoundWorkflowRun{
		ID:            value.GetId(),
		Status:        WorkflowRunStatus(value.GetStatus()),
		Target:        workflowTargetInputPtrFromTarget(value.GetTarget()),
		Trigger:       &trigger,
		CreatedAt:     timeFromTimestamp(value.GetCreatedAt()),
		StartedAt:     startedAt,
		CompletedAt:   completedAt,
		StatusMessage: value.GetStatusMessage(),
		ResultBody:    value.GetResultBody(),
		CreatedBy:     workflowActorInputPtrFromActor(value.GetCreatedBy()),
		ExecutionRef:  value.GetExecutionRef(),
		WorkflowKey:   value.GetWorkflowKey(),
	}, nil
}

// cloneBoundWorkflowRunProto creates a copy of an existing bound workflow run
// through the run input builder.
func cloneBoundWorkflowRunProto(value *proto.BoundWorkflowRun) (*proto.BoundWorkflowRun, error) {
	input, err := boundWorkflowRunFromProto(value)
	if err != nil || value == nil {
		return nil, err
	}
	return boundWorkflowRunToProto(input)
}

// boundWorkflowScheduleToProto creates a bound workflow schedule.
func boundWorkflowScheduleToProto(input BoundWorkflowSchedule) (*proto.BoundWorkflowSchedule, error) {
	target, err := newOptionalBoundWorkflowTarget(input.Target)
	if err != nil {
		return nil, err
	}
	return &proto.BoundWorkflowSchedule{
		Id:           input.ID,
		Cron:         input.Cron,
		Timezone:     input.Timezone,
		Target:       target,
		Paused:       input.Paused,
		CreatedAt:    timestampFromNonZeroTime(input.CreatedAt),
		UpdatedAt:    timestampFromNonZeroTime(input.UpdatedAt),
		NextRunAt:    timestampFromOptionalTime(input.NextRunAt),
		CreatedBy:    workflowActorFromInput(input.CreatedBy),
		ExecutionRef: input.ExecutionRef,
	}, nil
}

// boundWorkflowScheduleFromProto converts an existing protocol schedule
// into builder input.
func boundWorkflowScheduleFromProto(value *proto.BoundWorkflowSchedule) (BoundWorkflowSchedule, error) {
	if value == nil {
		return BoundWorkflowSchedule{}, nil
	}
	nextRunAt, err := timePtrFromTimestamp(value.GetNextRunAt())
	if err != nil {
		return BoundWorkflowSchedule{}, err
	}
	return BoundWorkflowSchedule{
		ID:           value.GetId(),
		Cron:         value.GetCron(),
		Timezone:     value.GetTimezone(),
		Target:       workflowTargetInputPtrFromTarget(value.GetTarget()),
		Paused:       value.GetPaused(),
		CreatedAt:    timeFromTimestamp(value.GetCreatedAt()),
		UpdatedAt:    timeFromTimestamp(value.GetUpdatedAt()),
		NextRunAt:    nextRunAt,
		CreatedBy:    workflowActorInputPtrFromActor(value.GetCreatedBy()),
		ExecutionRef: value.GetExecutionRef(),
	}, nil
}

// cloneBoundWorkflowScheduleProto creates a copy of an existing schedule
// through the schedule input builder.
func cloneBoundWorkflowScheduleProto(value *proto.BoundWorkflowSchedule) (*proto.BoundWorkflowSchedule, error) {
	input, err := boundWorkflowScheduleFromProto(value)
	if err != nil || value == nil {
		return nil, err
	}
	return boundWorkflowScheduleToProto(input)
}

// boundWorkflowEventTriggerToProto creates a bound workflow event trigger.
func boundWorkflowEventTriggerToProto(input BoundWorkflowEventTrigger) (*proto.BoundWorkflowEventTrigger, error) {
	target, err := newOptionalBoundWorkflowTarget(input.Target)
	if err != nil {
		return nil, err
	}
	return &proto.BoundWorkflowEventTrigger{
		Id:           input.ID,
		Match:        workflowEventMatchFromInput(input.Match),
		Target:       target,
		Paused:       input.Paused,
		CreatedAt:    timestampFromNonZeroTime(input.CreatedAt),
		UpdatedAt:    timestampFromNonZeroTime(input.UpdatedAt),
		CreatedBy:    workflowActorFromInput(input.CreatedBy),
		ExecutionRef: input.ExecutionRef,
	}, nil
}

// boundWorkflowEventTriggerFromProto converts an existing protocol event
// trigger into builder input.
func boundWorkflowEventTriggerFromProto(value *proto.BoundWorkflowEventTrigger) (BoundWorkflowEventTrigger, error) {
	if value == nil {
		return BoundWorkflowEventTrigger{}, nil
	}
	return BoundWorkflowEventTrigger{
		ID:           value.GetId(),
		Match:        workflowEventMatchInputPtrFromMatch(value.GetMatch()),
		Target:       workflowTargetInputPtrFromTarget(value.GetTarget()),
		Paused:       value.GetPaused(),
		CreatedAt:    timeFromTimestamp(value.GetCreatedAt()),
		UpdatedAt:    timeFromTimestamp(value.GetUpdatedAt()),
		CreatedBy:    workflowActorInputPtrFromActor(value.GetCreatedBy()),
		ExecutionRef: value.GetExecutionRef(),
	}, nil
}

// cloneBoundWorkflowEventTriggerProto creates a copy of an existing event
// trigger through the event trigger input builder.
func cloneBoundWorkflowEventTriggerProto(value *proto.BoundWorkflowEventTrigger) (*proto.BoundWorkflowEventTrigger, error) {
	input, err := boundWorkflowEventTriggerFromProto(value)
	if err != nil || value == nil {
		return nil, err
	}
	return boundWorkflowEventTriggerToProto(input)
}

// workflowExecutionReferenceToProto creates a workflow execution reference.
func workflowExecutionReferenceToProto(input WorkflowExecutionReference) (*proto.WorkflowExecutionReference, error) {
	target, err := newOptionalBoundWorkflowTarget(input.Target)
	if err != nil {
		return nil, err
	}
	return &proto.WorkflowExecutionReference{
		Id:                  input.ID,
		ProviderName:        input.ProviderName,
		Target:              target,
		SubjectId:           input.SubjectID,
		CredentialSubjectId: input.CredentialSubjectID,
		Permissions:         workflowAccessPermissionsFromInputs(input.Permissions),
		CreatedAt:           timestampFromNonZeroTime(input.CreatedAt),
		RevokedAt:           timestampFromOptionalTime(input.RevokedAt),
		SubjectKind:         input.SubjectKind,
		DisplayName:         input.DisplayName,
		AuthSource:          input.AuthSource,
		CallerPluginName:    input.CallerPluginName,
		RunAs:               workflowRunAsSubjectFromInput(input.RunAs),
		SourceDefinitionId:  input.SourceDefinitionID,
	}, nil
}

// workflowExecutionReferenceFromProto converts an existing protocol
// execution reference into builder input.
func workflowExecutionReferenceFromProto(value *proto.WorkflowExecutionReference) (WorkflowExecutionReference, error) {
	if value == nil {
		return WorkflowExecutionReference{}, nil
	}
	revokedAt, err := timePtrFromTimestamp(value.GetRevokedAt())
	if err != nil {
		return WorkflowExecutionReference{}, err
	}
	return WorkflowExecutionReference{
		ID:                  value.GetId(),
		ProviderName:        value.GetProviderName(),
		Target:              workflowTargetInputPtrFromTarget(value.GetTarget()),
		SubjectID:           value.GetSubjectId(),
		CredentialSubjectID: value.GetCredentialSubjectId(),
		Permissions:         workflowAccessPermissionInputsFromPermissions(value.GetPermissions()),
		CreatedAt:           timeFromTimestamp(value.GetCreatedAt()),
		RevokedAt:           revokedAt,
		SubjectKind:         value.GetSubjectKind(),
		DisplayName:         value.GetDisplayName(),
		AuthSource:          value.GetAuthSource(),
		CallerPluginName:    value.GetCallerPluginName(),
		RunAs:               workflowRunAsSubjectInputPtrFromSubject(value.GetRunAs()),
		SourceDefinitionID:  value.GetSourceDefinitionId(),
	}, nil
}

// cloneWorkflowExecutionReferenceProto creates a copy of an existing
// execution reference through the execution reference input builder.
func cloneWorkflowExecutionReferenceProto(value *proto.WorkflowExecutionReference) (*proto.WorkflowExecutionReference, error) {
	input, err := workflowExecutionReferenceFromProto(value)
	if err != nil || value == nil {
		return nil, err
	}
	return workflowExecutionReferenceToProto(input)
}

func timestampFromNonZeroTime(value time.Time) *timestamppb.Timestamp {
	if value.IsZero() {
		return nil
	}
	return timestamppb.New(value)
}

func timestampFromOptionalTime(value *time.Time) *timestamppb.Timestamp {
	if value == nil || value.IsZero() {
		return nil
	}
	return timestamppb.New(*value)
}

func newOptionalWorkflowOutputDelivery(input *WorkflowOutputDelivery) (*proto.WorkflowOutputDelivery, error) {
	if input == nil {
		return nil, nil
	}
	return workflowOutputDeliveryToProto(*input)
}

func newOptionalBoundWorkflowTarget(input *BoundWorkflowTarget) (*proto.BoundWorkflowTarget, error) {
	if input == nil {
		return nil, nil
	}
	return boundWorkflowTargetToProto(*input)
}

func newOptionalWorkflowRunTrigger(input *WorkflowRunTrigger) (*proto.WorkflowRunTrigger, error) {
	if input == nil {
		return nil, nil
	}
	return workflowRunTriggerToProto(*input)
}

func workflowTargetInputPtrFromTarget(value *proto.BoundWorkflowTarget) *BoundWorkflowTarget {
	if value == nil {
		return nil
	}
	input := boundWorkflowTargetFromProto(value)
	return &input
}

func workflowActorFromInput(input *WorkflowActor) *proto.WorkflowActor {
	if input == nil {
		return nil
	}
	return workflowActorToProto(*input)
}

func workflowActorInputPtrFromActor(value *proto.WorkflowActor) *WorkflowActor {
	if value == nil {
		return nil
	}
	input := workflowActorFromProto(value)
	return &input
}

func workflowEventMatchFromInput(input *WorkflowEventMatch) *proto.WorkflowEventMatch {
	if input == nil {
		return nil
	}
	return &proto.WorkflowEventMatch{
		Type:    input.Type,
		Source:  input.Source,
		Subject: input.Subject,
	}
}

func workflowEventMatchInputPtrFromMatch(value *proto.WorkflowEventMatch) *WorkflowEventMatch {
	if value == nil {
		return nil
	}
	return &WorkflowEventMatch{
		Type:    value.GetType(),
		Source:  value.GetSource(),
		Subject: value.GetSubject(),
	}
}

func workflowRunAsSubjectFromInput(input *WorkflowRunAsSubject) *proto.WorkflowRunAsSubject {
	if input == nil {
		return nil
	}
	return &proto.WorkflowRunAsSubject{
		SubjectId:   input.SubjectID,
		SubjectKind: input.SubjectKind,
		DisplayName: input.DisplayName,
		AuthSource:  input.AuthSource,
	}
}

func workflowRunAsSubjectInputPtrFromSubject(value *proto.WorkflowRunAsSubject) *WorkflowRunAsSubject {
	if value == nil {
		return nil
	}
	return &WorkflowRunAsSubject{
		SubjectID:   value.GetSubjectId(),
		SubjectKind: value.GetSubjectKind(),
		DisplayName: value.GetDisplayName(),
		AuthSource:  value.GetAuthSource(),
	}
}

func workflowAccessPermissionsFromInputs(values []WorkflowAccessPermission) []*proto.WorkflowAccessPermission {
	if len(values) == 0 {
		return nil
	}
	out := make([]*proto.WorkflowAccessPermission, 0, len(values))
	for _, value := range values {
		out = append(out, &proto.WorkflowAccessPermission{
			Plugin:     value.Plugin,
			Operations: append([]string(nil), value.Operations...),
		})
	}
	return out
}

func workflowAccessPermissionInputsFromPermissions(values []*proto.WorkflowAccessPermission) []WorkflowAccessPermission {
	if len(values) == 0 {
		return nil
	}
	out := make([]WorkflowAccessPermission, 0, len(values))
	for _, value := range values {
		if value == nil {
			continue
		}
		out = append(out, WorkflowAccessPermission{
			Plugin:     value.GetPlugin(),
			Operations: append([]string(nil), value.GetOperations()...),
		})
	}
	return out
}

func newWorkflowOutputBindings(values []WorkflowOutputBinding) ([]*proto.WorkflowOutputBinding, error) {
	if len(values) == 0 {
		return nil, nil
	}
	out := make([]*proto.WorkflowOutputBinding, 0, len(values))
	for _, value := range values {
		source, err := workflowOutputValueSourceFromInput(value.Value)
		if err != nil {
			return nil, err
		}
		out = append(out, &proto.WorkflowOutputBinding{
			InputField: value.InputField,
			Value:      source,
		})
	}
	return out, nil
}

func workflowOutputBindingInputsFromBindings(values []*proto.WorkflowOutputBinding) []WorkflowOutputBinding {
	if len(values) == 0 {
		return nil
	}
	out := make([]WorkflowOutputBinding, 0, len(values))
	for _, value := range values {
		if value == nil {
			continue
		}
		out = append(out, WorkflowOutputBinding{
			InputField: value.GetInputField(),
			Value:      workflowOutputValueSourceInputPtrFromSource(value.GetValue()),
		})
	}
	return out
}

func workflowOutputValueSourceFromInput(input *WorkflowOutputValueSource) (*proto.WorkflowOutputValueSource, error) {
	if input == nil {
		return nil, nil
	}
	selected := 0
	if input.AgentOutput != "" {
		selected++
	}
	if input.SignalPayload != "" {
		selected++
	}
	if input.SignalMetadata != "" {
		selected++
	}
	if input.Literal != nil {
		selected++
	}
	if input.AgentSession != "" {
		selected++
	}
	if selected == 0 {
		return &proto.WorkflowOutputValueSource{}, nil
	}
	if selected > 1 {
		return nil, fmt.Errorf("workflow output value source must set exactly one source")
	}
	switch {
	case input.AgentOutput != "":
		return &proto.WorkflowOutputValueSource{Kind: &proto.WorkflowOutputValueSource_AgentOutput{AgentOutput: input.AgentOutput}}, nil
	case input.SignalPayload != "":
		return &proto.WorkflowOutputValueSource{Kind: &proto.WorkflowOutputValueSource_SignalPayload{SignalPayload: input.SignalPayload}}, nil
	case input.SignalMetadata != "":
		return &proto.WorkflowOutputValueSource{Kind: &proto.WorkflowOutputValueSource_SignalMetadata{SignalMetadata: input.SignalMetadata}}, nil
	case input.AgentSession != "":
		return &proto.WorkflowOutputValueSource{Kind: &proto.WorkflowOutputValueSource_AgentSession{AgentSession: input.AgentSession}}, nil
	default:
		literal, err := valueFromAny(input.Literal)
		if err != nil {
			return nil, err
		}
		return &proto.WorkflowOutputValueSource{Kind: &proto.WorkflowOutputValueSource_Literal{Literal: literal}}, nil
	}
}

func workflowOutputValueSourceInputPtrFromSource(value *proto.WorkflowOutputValueSource) *WorkflowOutputValueSource {
	if value == nil {
		return nil
	}
	switch kind := value.GetKind().(type) {
	case *proto.WorkflowOutputValueSource_AgentOutput:
		return &WorkflowOutputValueSource{AgentOutput: kind.AgentOutput}
	case *proto.WorkflowOutputValueSource_SignalPayload:
		return &WorkflowOutputValueSource{SignalPayload: kind.SignalPayload}
	case *proto.WorkflowOutputValueSource_SignalMetadata:
		return &WorkflowOutputValueSource{SignalMetadata: kind.SignalMetadata}
	case *proto.WorkflowOutputValueSource_AgentSession:
		return &WorkflowOutputValueSource{AgentSession: kind.AgentSession}
	case *proto.WorkflowOutputValueSource_Literal:
		return &WorkflowOutputValueSource{Literal: anyFromValue(kind.Literal)}
	default:
		return &WorkflowOutputValueSource{}
	}
}
