// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/datastore.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexedDB_CreateObjectStore_FullMethodName = "/gestalt.provider.v1.IndexedDB/CreateObjectStore"
	IndexedDB_DeleteObjectStore_FullMethodName = "/gestalt.provider.v1.IndexedDB/DeleteObjectStore"
	IndexedDB_Get_FullMethodName               = "/gestalt.provider.v1.IndexedDB/Get"
	IndexedDB_GetKey_FullMethodName            = "/gestalt.provider.v1.IndexedDB/GetKey"
	IndexedDB_Add_FullMethodName               = "/gestalt.provider.v1.IndexedDB/Add"
	IndexedDB_Put_FullMethodName               = "/gestalt.provider.v1.IndexedDB/Put"
	IndexedDB_Delete_FullMethodName            = "/gestalt.provider.v1.IndexedDB/Delete"
	IndexedDB_Clear_FullMethodName             = "/gestalt.provider.v1.IndexedDB/Clear"
	IndexedDB_GetAll_FullMethodName            = "/gestalt.provider.v1.IndexedDB/GetAll"
	IndexedDB_GetAllKeys_FullMethodName        = "/gestalt.provider.v1.IndexedDB/GetAllKeys"
	IndexedDB_Count_FullMethodName             = "/gestalt.provider.v1.IndexedDB/Count"
	IndexedDB_DeleteRange_FullMethodName       = "/gestalt.provider.v1.IndexedDB/DeleteRange"
	IndexedDB_IndexGet_FullMethodName          = "/gestalt.provider.v1.IndexedDB/IndexGet"
	IndexedDB_IndexGetKey_FullMethodName       = "/gestalt.provider.v1.IndexedDB/IndexGetKey"
	IndexedDB_IndexGetAll_FullMethodName       = "/gestalt.provider.v1.IndexedDB/IndexGetAll"
	IndexedDB_IndexGetAllKeys_FullMethodName   = "/gestalt.provider.v1.IndexedDB/IndexGetAllKeys"
	IndexedDB_IndexCount_FullMethodName        = "/gestalt.provider.v1.IndexedDB/IndexCount"
	IndexedDB_IndexDelete_FullMethodName       = "/gestalt.provider.v1.IndexedDB/IndexDelete"
	IndexedDB_OpenCursor_FullMethodName        = "/gestalt.provider.v1.IndexedDB/OpenCursor"
	IndexedDB_Transaction_FullMethodName       = "/gestalt.provider.v1.IndexedDB/Transaction"
)

// IndexedDBClient is the client API for IndexedDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IndexedDB models the shared Gestalt IndexedDB-provider protocol.
type IndexedDBClient interface {
	// Lifecycle
	CreateObjectStore(ctx context.Context, in *CreateObjectStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteObjectStore(ctx context.Context, in *DeleteObjectStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Primary key CRUD
	Get(ctx context.Context, in *ObjectStoreRequest, opts ...grpc.CallOption) (*RecordResponse, error)
	GetKey(ctx context.Context, in *ObjectStoreRequest, opts ...grpc.CallOption) (*KeyResponse, error)
	Add(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Put(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *ObjectStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Bulk operations (with optional key range)
	Clear(ctx context.Context, in *ObjectStoreNameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAll(ctx context.Context, in *ObjectStoreRangeRequest, opts ...grpc.CallOption) (*RecordsResponse, error)
	GetAllKeys(ctx context.Context, in *ObjectStoreRangeRequest, opts ...grpc.CallOption) (*KeysResponse, error)
	Count(ctx context.Context, in *ObjectStoreRangeRequest, opts ...grpc.CallOption) (*CountResponse, error)
	DeleteRange(ctx context.Context, in *ObjectStoreRangeRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Index queries
	IndexGet(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*RecordResponse, error)
	IndexGetKey(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*KeyResponse, error)
	IndexGetAll(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*RecordsResponse, error)
	IndexGetAllKeys(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*KeysResponse, error)
	IndexCount(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*CountResponse, error)
	IndexDelete(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Cursor iteration (bidirectional stream)
	OpenCursor(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CursorClientMessage, CursorResponse], error)
	// Transaction stream. The first client message must be
	// BeginTransactionRequest. Stream close before commit aborts the transaction.
	Transaction(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransactionClientMessage, TransactionServerMessage], error)
}

type indexedDBClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexedDBClient(cc grpc.ClientConnInterface) IndexedDBClient {
	return &indexedDBClient{cc}
}

func (c *indexedDBClient) CreateObjectStore(ctx context.Context, in *CreateObjectStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IndexedDB_CreateObjectStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) DeleteObjectStore(ctx context.Context, in *DeleteObjectStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IndexedDB_DeleteObjectStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) Get(ctx context.Context, in *ObjectStoreRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, IndexedDB_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) GetKey(ctx context.Context, in *ObjectStoreRequest, opts ...grpc.CallOption) (*KeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyResponse)
	err := c.cc.Invoke(ctx, IndexedDB_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) Add(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IndexedDB_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) Put(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IndexedDB_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) Delete(ctx context.Context, in *ObjectStoreRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IndexedDB_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) Clear(ctx context.Context, in *ObjectStoreNameRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, IndexedDB_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) GetAll(ctx context.Context, in *ObjectStoreRangeRequest, opts ...grpc.CallOption) (*RecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordsResponse)
	err := c.cc.Invoke(ctx, IndexedDB_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) GetAllKeys(ctx context.Context, in *ObjectStoreRangeRequest, opts ...grpc.CallOption) (*KeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeysResponse)
	err := c.cc.Invoke(ctx, IndexedDB_GetAllKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) Count(ctx context.Context, in *ObjectStoreRangeRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, IndexedDB_Count_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) DeleteRange(ctx context.Context, in *ObjectStoreRangeRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, IndexedDB_DeleteRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) IndexGet(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, IndexedDB_IndexGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) IndexGetKey(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*KeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyResponse)
	err := c.cc.Invoke(ctx, IndexedDB_IndexGetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) IndexGetAll(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*RecordsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordsResponse)
	err := c.cc.Invoke(ctx, IndexedDB_IndexGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) IndexGetAllKeys(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*KeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeysResponse)
	err := c.cc.Invoke(ctx, IndexedDB_IndexGetAllKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) IndexCount(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, IndexedDB_IndexCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) IndexDelete(ctx context.Context, in *IndexQueryRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, IndexedDB_IndexDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexedDBClient) OpenCursor(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CursorClientMessage, CursorResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IndexedDB_ServiceDesc.Streams[0], IndexedDB_OpenCursor_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CursorClientMessage, CursorResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexedDB_OpenCursorClient = grpc.BidiStreamingClient[CursorClientMessage, CursorResponse]

func (c *indexedDBClient) Transaction(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransactionClientMessage, TransactionServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IndexedDB_ServiceDesc.Streams[1], IndexedDB_Transaction_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransactionClientMessage, TransactionServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexedDB_TransactionClient = grpc.BidiStreamingClient[TransactionClientMessage, TransactionServerMessage]

// IndexedDBServer is the server API for IndexedDB service.
// All implementations must embed UnimplementedIndexedDBServer
// for forward compatibility.
//
// IndexedDB models the shared Gestalt IndexedDB-provider protocol.
type IndexedDBServer interface {
	// Lifecycle
	CreateObjectStore(context.Context, *CreateObjectStoreRequest) (*emptypb.Empty, error)
	DeleteObjectStore(context.Context, *DeleteObjectStoreRequest) (*emptypb.Empty, error)
	// Primary key CRUD
	Get(context.Context, *ObjectStoreRequest) (*RecordResponse, error)
	GetKey(context.Context, *ObjectStoreRequest) (*KeyResponse, error)
	Add(context.Context, *RecordRequest) (*emptypb.Empty, error)
	Put(context.Context, *RecordRequest) (*emptypb.Empty, error)
	Delete(context.Context, *ObjectStoreRequest) (*emptypb.Empty, error)
	// Bulk operations (with optional key range)
	Clear(context.Context, *ObjectStoreNameRequest) (*emptypb.Empty, error)
	GetAll(context.Context, *ObjectStoreRangeRequest) (*RecordsResponse, error)
	GetAllKeys(context.Context, *ObjectStoreRangeRequest) (*KeysResponse, error)
	Count(context.Context, *ObjectStoreRangeRequest) (*CountResponse, error)
	DeleteRange(context.Context, *ObjectStoreRangeRequest) (*DeleteResponse, error)
	// Index queries
	IndexGet(context.Context, *IndexQueryRequest) (*RecordResponse, error)
	IndexGetKey(context.Context, *IndexQueryRequest) (*KeyResponse, error)
	IndexGetAll(context.Context, *IndexQueryRequest) (*RecordsResponse, error)
	IndexGetAllKeys(context.Context, *IndexQueryRequest) (*KeysResponse, error)
	IndexCount(context.Context, *IndexQueryRequest) (*CountResponse, error)
	IndexDelete(context.Context, *IndexQueryRequest) (*DeleteResponse, error)
	// Cursor iteration (bidirectional stream)
	OpenCursor(grpc.BidiStreamingServer[CursorClientMessage, CursorResponse]) error
	// Transaction stream. The first client message must be
	// BeginTransactionRequest. Stream close before commit aborts the transaction.
	Transaction(grpc.BidiStreamingServer[TransactionClientMessage, TransactionServerMessage]) error
	mustEmbedUnimplementedIndexedDBServer()
}

// UnimplementedIndexedDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexedDBServer struct{}

func (UnimplementedIndexedDBServer) CreateObjectStore(context.Context, *CreateObjectStoreRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateObjectStore not implemented")
}
func (UnimplementedIndexedDBServer) DeleteObjectStore(context.Context, *DeleteObjectStoreRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObjectStore not implemented")
}
func (UnimplementedIndexedDBServer) Get(context.Context, *ObjectStoreRequest) (*RecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedIndexedDBServer) GetKey(context.Context, *ObjectStoreRequest) (*KeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedIndexedDBServer) Add(context.Context, *RecordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedIndexedDBServer) Put(context.Context, *RecordRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedIndexedDBServer) Delete(context.Context, *ObjectStoreRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedIndexedDBServer) Clear(context.Context, *ObjectStoreNameRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedIndexedDBServer) GetAll(context.Context, *ObjectStoreRangeRequest) (*RecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedIndexedDBServer) GetAllKeys(context.Context, *ObjectStoreRangeRequest) (*KeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllKeys not implemented")
}
func (UnimplementedIndexedDBServer) Count(context.Context, *ObjectStoreRangeRequest) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedIndexedDBServer) DeleteRange(context.Context, *ObjectStoreRangeRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRange not implemented")
}
func (UnimplementedIndexedDBServer) IndexGet(context.Context, *IndexQueryRequest) (*RecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexGet not implemented")
}
func (UnimplementedIndexedDBServer) IndexGetKey(context.Context, *IndexQueryRequest) (*KeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexGetKey not implemented")
}
func (UnimplementedIndexedDBServer) IndexGetAll(context.Context, *IndexQueryRequest) (*RecordsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexGetAll not implemented")
}
func (UnimplementedIndexedDBServer) IndexGetAllKeys(context.Context, *IndexQueryRequest) (*KeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexGetAllKeys not implemented")
}
func (UnimplementedIndexedDBServer) IndexCount(context.Context, *IndexQueryRequest) (*CountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexCount not implemented")
}
func (UnimplementedIndexedDBServer) IndexDelete(context.Context, *IndexQueryRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IndexDelete not implemented")
}
func (UnimplementedIndexedDBServer) OpenCursor(grpc.BidiStreamingServer[CursorClientMessage, CursorResponse]) error {
	return status.Error(codes.Unimplemented, "method OpenCursor not implemented")
}
func (UnimplementedIndexedDBServer) Transaction(grpc.BidiStreamingServer[TransactionClientMessage, TransactionServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Transaction not implemented")
}
func (UnimplementedIndexedDBServer) mustEmbedUnimplementedIndexedDBServer() {}
func (UnimplementedIndexedDBServer) testEmbeddedByValue()                   {}

// UnsafeIndexedDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexedDBServer will
// result in compilation errors.
type UnsafeIndexedDBServer interface {
	mustEmbedUnimplementedIndexedDBServer()
}

func RegisterIndexedDBServer(s grpc.ServiceRegistrar, srv IndexedDBServer) {
	// If the following call panics, it indicates UnimplementedIndexedDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexedDB_ServiceDesc, srv)
}

func _IndexedDB_CreateObjectStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).CreateObjectStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_CreateObjectStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).CreateObjectStore(ctx, req.(*CreateObjectStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_DeleteObjectStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).DeleteObjectStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_DeleteObjectStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).DeleteObjectStore(ctx, req.(*DeleteObjectStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).Get(ctx, req.(*ObjectStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).GetKey(ctx, req.(*ObjectStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).Add(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).Put(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).Delete(ctx, req.(*ObjectStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectStoreNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).Clear(ctx, req.(*ObjectStoreNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectStoreRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).GetAll(ctx, req.(*ObjectStoreRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_GetAllKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectStoreRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).GetAllKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_GetAllKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).GetAllKeys(ctx, req.(*ObjectStoreRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectStoreRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_Count_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).Count(ctx, req.(*ObjectStoreRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_DeleteRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectStoreRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).DeleteRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_DeleteRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).DeleteRange(ctx, req.(*ObjectStoreRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_IndexGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).IndexGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_IndexGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).IndexGet(ctx, req.(*IndexQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_IndexGetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).IndexGetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_IndexGetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).IndexGetKey(ctx, req.(*IndexQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_IndexGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).IndexGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_IndexGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).IndexGetAll(ctx, req.(*IndexQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_IndexGetAllKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).IndexGetAllKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_IndexGetAllKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).IndexGetAllKeys(ctx, req.(*IndexQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_IndexCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).IndexCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_IndexCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).IndexCount(ctx, req.(*IndexQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_IndexDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexedDBServer).IndexDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexedDB_IndexDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexedDBServer).IndexDelete(ctx, req.(*IndexQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexedDB_OpenCursor_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IndexedDBServer).OpenCursor(&grpc.GenericServerStream[CursorClientMessage, CursorResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexedDB_OpenCursorServer = grpc.BidiStreamingServer[CursorClientMessage, CursorResponse]

func _IndexedDB_Transaction_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IndexedDBServer).Transaction(&grpc.GenericServerStream[TransactionClientMessage, TransactionServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IndexedDB_TransactionServer = grpc.BidiStreamingServer[TransactionClientMessage, TransactionServerMessage]

// IndexedDB_ServiceDesc is the grpc.ServiceDesc for IndexedDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexedDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gestalt.provider.v1.IndexedDB",
	HandlerType: (*IndexedDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateObjectStore",
			Handler:    _IndexedDB_CreateObjectStore_Handler,
		},
		{
			MethodName: "DeleteObjectStore",
			Handler:    _IndexedDB_DeleteObjectStore_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _IndexedDB_Get_Handler,
		},
		{
			MethodName: "GetKey",
			Handler:    _IndexedDB_GetKey_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _IndexedDB_Add_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _IndexedDB_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _IndexedDB_Delete_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _IndexedDB_Clear_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _IndexedDB_GetAll_Handler,
		},
		{
			MethodName: "GetAllKeys",
			Handler:    _IndexedDB_GetAllKeys_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _IndexedDB_Count_Handler,
		},
		{
			MethodName: "DeleteRange",
			Handler:    _IndexedDB_DeleteRange_Handler,
		},
		{
			MethodName: "IndexGet",
			Handler:    _IndexedDB_IndexGet_Handler,
		},
		{
			MethodName: "IndexGetKey",
			Handler:    _IndexedDB_IndexGetKey_Handler,
		},
		{
			MethodName: "IndexGetAll",
			Handler:    _IndexedDB_IndexGetAll_Handler,
		},
		{
			MethodName: "IndexGetAllKeys",
			Handler:    _IndexedDB_IndexGetAllKeys_Handler,
		},
		{
			MethodName: "IndexCount",
			Handler:    _IndexedDB_IndexCount_Handler,
		},
		{
			MethodName: "IndexDelete",
			Handler:    _IndexedDB_IndexDelete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenCursor",
			Handler:       _IndexedDB_OpenCursor_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Transaction",
			Handler:       _IndexedDB_Transaction_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "v1/datastore.proto",
}
