GITHUB_API_VERSION = "2022-11-28"
GITHUB_DEFAULT_API_BASE_URL = "https://api.github.com"
GITHUB_DEFAULT_GRAPHQL_BASE_URL = "https://api.github.com/graphql"
GITHUB_DEFAULT_WEB_BASE_URL = "https://github.com"

EXTERNAL_IDENTITY_TYPE_METADATA_KEY = "gestalt.external_identity.type"
EXTERNAL_IDENTITY_ID_METADATA_KEY = "gestalt.external_identity.id"
GITHUB_EXTERNAL_IDENTITY_TYPE = "github_identity"

GITHUB_EVENT_OPERATION = "events.handle"
REVIEW_PULL_REQUEST_OPERATION = "reviewPullRequest"
BOT_COMMIT_FILES_OPERATION = "bot.commitFiles"
BOT_OPEN_PULL_REQUEST_OPERATION = "bot.openPullRequest"
BOT_CLOSE_PULL_REQUEST_OPERATION = "bot.closePullRequest"
BOT_CREATE_PULL_REQUEST_OPERATION = "bot.createPullRequest"
BOT_CREATE_PULL_REQUEST_REVIEW_OPERATION = "bot.createPullRequestReview"
BOT_LIST_PULL_REQUEST_REVIEW_THREADS_OPERATION = "bot.listPullRequestReviewThreads"
BOT_RESOLVE_PULL_REQUEST_REVIEW_THREAD_OPERATION = "bot.resolvePullRequestReviewThread"
BOT_CREATE_PULL_REQUEST_CONVERSATION_COMMENT_OPERATION = (
    "bot.createPullRequestConversationComment"
)
BOT_CREATE_ISSUE_COMMENT_OPERATION = "bot.createIssueComment"
BOT_ADD_REACTION_OPERATION = "bot.addReaction"
BOT_ADD_LABELS_OPERATION = "bot.addLabels"
BOT_REMOVE_LABELS_OPERATION = "bot.removeLabels"
BOT_REQUEST_REVIEWERS_OPERATION = "bot.requestReviewers"
BOT_GET_PULL_REQUEST_OPERATION = "bot.getPullRequest"
BOT_LIST_PULL_REQUEST_FILES_OPERATION = "bot.listPullRequestFiles"
BOT_GET_CHECK_RUN_OPERATION = "bot.getCheckRun"
BOT_LIST_CHECK_RUN_ANNOTATIONS_OPERATION = "bot.listCheckRunAnnotations"
BOT_GET_WORKFLOW_RUN_OPERATION = "bot.getWorkflowRun"
BOT_LIST_WORKFLOW_RUN_JOBS_OPERATION = "bot.listWorkflowRunJobs"

BOT_OPERATION_ORDER = (
    BOT_GET_PULL_REQUEST_OPERATION,
    BOT_LIST_PULL_REQUEST_FILES_OPERATION,
    BOT_LIST_PULL_REQUEST_REVIEW_THREADS_OPERATION,
    BOT_GET_CHECK_RUN_OPERATION,
    BOT_LIST_CHECK_RUN_ANNOTATIONS_OPERATION,
    BOT_GET_WORKFLOW_RUN_OPERATION,
    BOT_LIST_WORKFLOW_RUN_JOBS_OPERATION,
    BOT_CREATE_PULL_REQUEST_REVIEW_OPERATION,
    BOT_RESOLVE_PULL_REQUEST_REVIEW_THREAD_OPERATION,
    BOT_CREATE_PULL_REQUEST_CONVERSATION_COMMENT_OPERATION,
    BOT_CREATE_ISSUE_COMMENT_OPERATION,
    BOT_ADD_REACTION_OPERATION,
    BOT_ADD_LABELS_OPERATION,
    BOT_REMOVE_LABELS_OPERATION,
    BOT_REQUEST_REVIEWERS_OPERATION,
    BOT_COMMIT_FILES_OPERATION,
    BOT_OPEN_PULL_REQUEST_OPERATION,
    BOT_CLOSE_PULL_REQUEST_OPERATION,
    BOT_CREATE_PULL_REQUEST_OPERATION,
)

BOT_READ_OPERATIONS = (
    BOT_GET_PULL_REQUEST_OPERATION,
    BOT_LIST_PULL_REQUEST_FILES_OPERATION,
    BOT_LIST_PULL_REQUEST_REVIEW_THREADS_OPERATION,
    BOT_GET_CHECK_RUN_OPERATION,
    BOT_LIST_CHECK_RUN_ANNOTATIONS_OPERATION,
    BOT_GET_WORKFLOW_RUN_OPERATION,
    BOT_LIST_WORKFLOW_RUN_JOBS_OPERATION,
)

WEBHOOK_POLICY_OBSERVE_MODE = "observe"
WEBHOOK_POLICY_COMMENT_MODE = "comment"
WEBHOOK_POLICY_BRANCH_COMMIT_MODE = "branch_commit"
WEBHOOK_POLICY_PULL_REQUEST_MODE = "pull_request"

WEBHOOK_POLICY_ACTION_MODES = (
    WEBHOOK_POLICY_OBSERVE_MODE,
    WEBHOOK_POLICY_COMMENT_MODE,
    WEBHOOK_POLICY_BRANCH_COMMIT_MODE,
    WEBHOOK_POLICY_PULL_REQUEST_MODE,
)

DEFAULT_POLICY_OPERATIONS_BY_MODE = {
    WEBHOOK_POLICY_OBSERVE_MODE: BOT_READ_OPERATIONS,
    WEBHOOK_POLICY_COMMENT_MODE: (
        *BOT_READ_OPERATIONS,
        BOT_CREATE_PULL_REQUEST_REVIEW_OPERATION,
        BOT_CREATE_PULL_REQUEST_CONVERSATION_COMMENT_OPERATION,
        BOT_CREATE_ISSUE_COMMENT_OPERATION,
    ),
    WEBHOOK_POLICY_BRANCH_COMMIT_MODE: (
        *BOT_READ_OPERATIONS,
        BOT_COMMIT_FILES_OPERATION,
    ),
    WEBHOOK_POLICY_PULL_REQUEST_MODE: (
        *BOT_READ_OPERATIONS,
        BOT_CREATE_PULL_REQUEST_REVIEW_OPERATION,
        BOT_CREATE_PULL_REQUEST_CONVERSATION_COMMENT_OPERATION,
        BOT_CREATE_ISSUE_COMMENT_OPERATION,
        BOT_COMMIT_FILES_OPERATION,
        BOT_OPEN_PULL_REQUEST_OPERATION,
        BOT_CREATE_PULL_REQUEST_OPERATION,
    ),
}

GITHUB_WORKFLOW_SIGNAL_NAME = "github.app.webhook"

GITHUB_INSTALLATION_SUBJECT_PREFIX = "service_account:github_app_installation:"
GITHUB_REPOSITORY_SUBJECT_SEPARATOR = ":repo:"

DEFAULT_WEBHOOK_EVENTS = (
    "check_run",
    "check_suite",
    "issue_comment",
    "issues",
    "pull_request",
    "pull_request_review",
    "pull_request_review_comment",
    "workflow_run",
)

DEFAULT_AGENT_SYSTEM_PROMPT = """
You are a GitHub App bot running inside Gestalt.
You are responding to a verified GitHub App webhook, not a user OAuth connection.
Use the available GitHub bot tools to inspect or change GitHub state.
When you create commits or pull requests, use the installation_id and repository
details from the event unless the user instruction says otherwise.
Return a concise final summary of what you did.
""".strip()
MAX_AGENT_USER_PROMPT_CHARS = 12000
MAX_GITHUB_BODY_CHARS = 4096
MAX_GITHUB_PATCH_CHARS = 8192
MAX_GITHUB_TITLE_CHARS = 512
